export type PromptItem = {
  id: string;
  title: string;
  slug: string;
  legacySlug?: string;
  category: string;
  categoryName?: string;
  categorySlug: string;
  tags: string[];
  coverImage: string;
  image?: string;
  imageUrl?: string;
  galleryImages: string[];
  imageFit?: "cover" | "contain";
  displayType?: "landscape" | "portrait" | "poster" | "product" | "ui" | "icon" | "scene";
  englishPrompt: string;
  enPrompt?: string;
  chinesePrompt: string;
  cnPrompt?: string;
  zhPrompt?: string;
  description: string;
  sourceUrl: string;
  sourceName?: string;
  sourceRepo?: string;
  sourceLicense?: string;
  license?: string;
  originalSourceUrl?: string;
  aspectRatio?: string;
  aspectRatioLabel?: string;
  imageWidth?: number;
  imageHeight?: number;
  ratio?: string;
  model?: string;
  style?: string;
  useCases: string[];
  useCase?: string;
  views?: number;
  favorites?: number;
  likes?: number;
  createdAt?: string;
  updatedAt?: string;
  isFeatured?: boolean;
};

export type PromptSort = "latest" | "popular" | "favorites";
